In [1]:
import pandas as pd

In [22]:
df = pd.read_json("characters.json")

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1532 entries, 0 to 1531
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  1532 non-null   str
 1   image                 1532 non-null   str
 2   affiliation           1274 non-null   str
 3   first_appearance_arc  1532 non-null   str
 4   race                  1532 non-null   str
 5   status                1532 non-null   str
 6   description           1532 non-null   str
 7   journey               1496 non-null   object
 8   relationships         1356 non-null   object
 9   epithet               261 non-null    str
 10  devil_fruit           223 non-null    object
 11  origin                593 non-null    str
 12  height                428 non-null    float64
 13  age                   530 non-null    object
 14  image_pre             113 non-null    str
 15  haki                  184 non-null    object
 16  bounty                222 non-null    object
dtypes: float64(1), object(6), str(10)
memory usage: 459.6+ KB

In [ ]:
characters = df.drop(columns=["image","first_appearance_arc","description","journey","relationships","epithet","age","height","image_pre"])

In [37]:
characters.head()

,name,affiliation,race,status,devil_fruit,origin,haki,bounty
0,A O,A O Pirates,Human,Unknown,NaN,NaN,NaN,NaN
1,Abdullah,Ideo Pirates,Human,Alive,NaN,NaN,NaN,NaN
2,Absalom,Thriller Bark Pirates,Human,Deceased,Suke Suke no Mi,West Blue,NaN,NaN
3,Acilia,NaN,Human,Alive,NaN,NaN,NaN,NaN
4,Adele,Mermaid Café,Merfolk,Alive,NaN,Grand Line,NaN,NaN

In [38]:
devil_fruits = pd.read_json("devil_fruits.json")

In [39]:
devil_fruits.head()

,name,english,image,image_pre,type,user,description,subtype
0,Bara Bara no Mi,Chop-Chop Fruit,/images/devil_fruits/barabara.webp,/images/devil_fruits/barabarausage.webp,Paramecia,Buggy,Allows the user to split their body into indep...,NaN
1,Sube Sube no Mi,Slip-Slip Fruit,/images/devil_fruits/subesube.webp,/images/devil_fruits/subesubeusage.webp,Paramecia,Alvida,"Allows the user to have an incredibly smooth, ...",NaN
2,Bomu Bomu no Mi,Boom-Boom Fruit,/images/devil_fruits/bomubomu.webp,/images/devil_fruits/bomubomuusage.webp,Paramecia,Gem [Mr. 5],Allows the user to make any part of their body...,NaN
3,Kiro Kiro no Mi,Kilo-Kilo Fruit,/images/devil_fruits/kirokiro.webp,/images/devil_fruits/kirokirousage.webp,Paramecia,Mikita [Miss Valentine],Allows the user to manipulate the weight of th...,NaN
4,Hana Hana no Mi,Flower-Flower Fruit,/images/devil_fruits/hanahana.webp,/images/devil_fruits/hanahanausage.webp,Paramecia,Nico Robin,Allows the user to sprout extra body parts fro...,NaN

In [111]:
len(devil_fruits[devil_fruits["name"]=="bat SMILE"])

0

In [124]:
def findtype(fruit_name):
    if(type(fruit_name) is list):
        
        return(["Logia","Paramecia"])
        
    fruit = devil_fruits[devil_fruits["name"]==" "+fruit_name] #This line is to fix, for example "bat SMILE" has 2 spaces before
    fruit.reset_index(inplace=True)
    if(len(fruit)>0):
        return fruit["type"][0]
    else:
        return("Unknown")

In [113]:
print(findtype("bat SMILE"))

Unknown

In [ ]:
characters["devil_fruit"] = characters["devil_fruit"].fillna("Unknown")

In [102]:
devil_fruits["type"].unique()

<ArrowStringArray>
['Paramecia', 'Logia', 'Zoan', 'Unknown']
Length: 4, dtype: str

In [137]:
list_type = []
for fruit in characters["devil_fruit"]:
    print(fruit)
    
    if(fruit=="Unknown"):
        list_type.append("Unknown")
    else:
        list_type.append(findtype(fruit))
print(list_type)

Unknown
Unknown
Suke Suke no Mi
Unknown
Unknown
Unknown
Swallowtail Butterfly SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Alpaca SMILE
Unknown
Sube Sube no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Mori Mori no Mi
Ryu Ryu no Mi, Model: Pteranodon
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Shima Shima no Mi
Unknown
Unknown
Elephant SMILE
Unknown
Unknown
Buki Buki no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Flying Squirrel SMILE
Unknown
Unknown
Unknown
Unknown
Nikyu Nikyu no Mi
Bari Bari no Mi
Unknown
Wara Wara no Mi
Unknown
Unknown
Unknown
Bat SMILE
Gastrimargus Grasshopper SMILE
Unknown
Unknown
Wasp SMILE
Unknown
Rhino Beetle SMILE
Unknown
Unknown
Unknown
Bane Bane no Mi
Unknown
Kobu Kobu no Mi
Unknown
Unknown
Mane Mane no Mi
Unknown
Mushi Mushi no Mi, Model: Suzumebachi
Iku Iku no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Python SMILE
Hedgehog SMILE
Unknown
Unknown
Unknown
Unknown
Kumo Kumo no Mi, Model: Rosamygale Grauvogeli
Unknown
Unknown
Unknown
Poke Poke no Mi
Unknown
Unknown
Unknown
Unknown
Nori Nori no Mi
Unknown
Doa Doa no Mi
Unknown
Mero Mero no Mi
Hebi Hebi no Mi, Model: King Cobra
Hebi Hebi no Mi, Model: Anaconda
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Pika Pika no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Gorilla SMILE (2)
Unknown
Unknown
Unknown
Yomi Yomi no Mi
Unknown
Unknown
Unknown
Unknown
Guru Guru no Mi
Bara Bara no Mi
Unknown
Unknown
Unknown
Inu Inu no Mi, Model: Tanuki
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Gasu Gasu no Mi
Caiman SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Shiro Shiro no Mi
Unknown
Unknown
Numa Numa no Mi
Soru Soru no Mi
Unknown
Unknown
Unknown
Inu Inu no Mi, Model: Kyubi no Kitsune
Caucasus Beetle SMILE
Unknown
Unknown
Unknown
Unnamed Cerberus Zoan (Awakened)
Unknown
Unknown
Unknown
Inu Inu no Mi, Model: Jackal
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Mira Mira no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Bisu Bisu no Mi
Unknown
Unknown
Hoya Hoya no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Bata Bata no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Mochi Mochi no Mi (Awakened)
Unknown
Unknown
Soru Soru no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Buku Buku no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Gocha Gocha no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Kuri Kuri no Mi
Netsu Netsu no Mi
Unknown
Pero Pero no Mi
Unknown
Unknown
Unknown
Memo Memo no Mi
Unknown
Unknown
Shibo Shibo no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Phasmid SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Suna Suna no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Ostrich SMILE
Unknown
Unknown
Unknown
Unknown
Scorpion SMILE
Unknown
Unknown
Unknown
Unknown
Unnamed Dalmatian Zoan
Ushi Ushi no Mi, Model: Bison
Unknown
Unknown
Unknown
Unknown
Unknown
Supa Supa no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Hira Hira no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Hippopotamus SMILE
Shiku Shiku no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ito Ito no Mi (Awakened)
Unknown
Unknown
Nagi Nagi no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Owl SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Mogu Mogu no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Gura Gura no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Horu Horu no Mi
Goro Goro no Mi
Unknown
Unnamed Caterpillar Zoan
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Jiki Jiki no Mi (Awakened)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Chicken SMILE
Noro Noro no Mi
Unknown
Unknown
Horse SMILE (4)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Zou Zou no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Doru Doru no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Bomu Bomu no Mi
Unknown
Unknown
Unknown
Unknown
Gazelle SMILE
Unknown
Bomu Bomu no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Horo Horo no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Squirrel SMILE
Ato Ato no Mi
Unknown
Unknown
Unknown
Unknown
Pamu Pamu no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Giraffe SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Hawk SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ori Ori no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Horse SMILE (2)
Lion SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Horse SMILE (3)
Unknown
Unknown
Unknown
Inu Inu no Mi, Model: Hound
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Choki Choki no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Zushi Zushi no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Inu Inu no Mi, Model: Wolf
Zou Zou no Mi, Model: Mammoth
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Riki Riki no Mi
Unknown
Toshi Toshi no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Jiki Jiki no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Hito Hito no Mi, Model: Nika (Awakened)
Kira Kira no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Chinese Grasshopper SMILE
Unknown
Mushi Mushi no Mi, Model: Kabutomushi
Unknown
Unknown
Unknown
Uo Uo no Mi, Model: Seiryu
Unknown
Unknown
Unknown
Ushi Ushi no Mi, Model: Giraffe (Awakened)
Unknown
Unknown
Unknown
Unknown
Awa Awa no Mi
Unknown
Praying Mantis SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Susu Susu no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Jake Jake no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Fuku Fuku no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Peregrine Falcon SMILE
Unknown
Unknown
Unknown
Unknown
Uo Uo no Mi, Model: Seiryu (Artificial)
Kage Kage no Mi
Unknown
Unknown
Toki Toki no Mi
Unknown
Unknown
Unknown
Unknown
Muchi Muchi no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Mane Mane no Mi
Fude Fude no Mi
Hebi Hebi no Mi, Model: Yamata no Orochi
Bari Bari no Mi
Kibi Kibi no Mi
Hie Hie no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unnamed Wings Devil Fruit
Unknown
Unknown
Inu Inu no Mi, Model: Dachshund
Unknown
Nui Nui no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Nidhogg
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ton Ton no Mi
Unknown
Unknown
Armadillo SMILE
Unknown
Doku Doku no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Chiyu Chiyu no Mi
Tori Tori no Mi, Model: Phoenix
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
['Yami Yami no Mi', ' Gura Gura No Mi']
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Kiro Kiro no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unnamed Chihuahua Zoan (Failed Awakened)
Unnamed Koala Zoan (Failed Awakened)
Unnamed Rhinoceros Zoan (Failed Awakened)
Unknown
Unnamed Cow Zoan (Failed Awakened)
Unnamed Zebra Zoan (Failed Awakened)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Gorilla SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Yuki Yuki no Mi
Unknown
Unknown
Unknown
Unknown
Hito Hito no Mi, Model: Nika (Awakened)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Tori Tori no Mi, Model: Albatross
Oshi Oshi no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Mouse SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Akuma No Mi (Awakened)
Unknown
Unknown
Hana Hana no Mi
Unknown
Crab SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Japanese Stag Beetle SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Hognose Snake SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unnamed Spider Zoan
Hito Hito no Mi, Model: Onyudo
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Spinosaurus
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Kame Kame no Mi
Tori Tori no Mi, Model: Falcon
Unknown
Unknown
Unknown
Horo Horo no Mi
Unknown
Unknown
Ishi Ishi no Mi
Unknown
Uma Uma no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Rattlesnake SMILE
Unknown
Unknown
Rako Rako no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Mera Mera no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Gunyo Gunyo no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Rabbit SMILE
Unknown
Unknown
Unnamed Squirrel Zoan
Unknown
Unknown
Maki Maki no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Wolf SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Qilin (Awakened)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Neko Neko no Mi, Model: Leopard (Awakened)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Mera Mera no Mi
Unknown
Unknown
Unknown
Rhino SMILE
Magu Magu no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Deka Deka no Mi
Unknown
Unknown
Snake SMILE (2)
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Triceratops
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Brachiosaurus
Unknown
Unknown
Scorpion SMILE (2)
Unknown
Unknown
Oto Oto no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Hito Hito no Mi, Model: Daibutsu
Unknown
Sui Sui no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Shari Shari no Mi
Sheep SMILE
Unknown
Unknown
Iba Iba no Mi
Fuwa Fuwa no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Juku Juku no Mi
Unknown
Unknown
Unknown
Unknown
Suke Suke no Mi
Unknown
Unknown
Sabi Sabi no Mi
Unknown
Aro Aro no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Sara Sara no Mi, Model: Axolotl
Moku Moku no Mi
Unknown
Snake SMILE
Unknown
Monkey SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Horse SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Kuku Kuku no Mi
Unknown
Uma Uma no Mi, Model: Pegasus
Batto Batto no Mi
Unknown
Unknown
Hobi Hobi no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Tama Tama no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
White Snake SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Hito Hito no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ope Ope no Mi (Awakened)
Unknown
Beta Beta no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Woshu Woshu no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Pachycephalosaurus
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Tsutsu Tsutsu no Mi
Unnamed Paramecia
Unknown
Unknown
Unknown
Unknown
Giant Tortoise SMILE
Unknown
Unknown
Unknown
Unknown
Unknown
Wapu Wapu no Mi
Unknown
Mato Mato no Mi
Gabu Gabu no Mi
Unknown
Unknown
Nomi Nomi no Mi
Unknown
Beri Beri no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Giro Giro no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Pug SMILE
Unknown
Baku Baku no Mi
Unknown
Unknown
Ryu Ryu no Mi, Model: Nidhogg
Unknown
Unknown
Unknown
Unknown
Neko Neko no Mi, Model: Saber Tiger
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Ryu Ryu no Mi, Model: Allosaurus
Unknown
Unknown
Japanese Rat Snake SMILE
Inu Inu no Mi, Model: Okuchi no Makami
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Toge Toge no Mi
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown

In [149]:
list_type_df = pd.DataFrame(list_type.copy())
list_type_df = list_type_df.rename(columns={0:"devil_fruit_type"})

In [150]:
list_type_df.head()

  devil_fruit_type
0          Unknown
1          Unknown
2        Paramecia
3          Unknown
4          Unknown

In [155]:
characters = characters.join(list_type_df)

In [156]:
characters.to_csv("characters_current.csv")